name: recipe
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/italian_food.jpg
    - assets/images/persian_food.jpg
    - assets/images/german_food.jpg
    - assets/images/american_food.jpg
    - assets/images/french_food.jpg
    - assets/images/spanish_food.jpg
    - assets/images/turkish_food.jpg
    - assets/images/mexican_food.jpg
    - assets/images/spaghetti_carbonara.jpg
    - assets/images/margherita_pizza.jpg
    - assets/images/chicken_alfredo.jpg
    - assets/images/caesar_salad.jpg
    - assets/images/risotto_milanese.jpg
    - assets/images/gnocchi_pesto.jpg
    - assets/images/osso_buco.jpg
    - assets/images/tiramisu.jpg
    - assets/images/caprese_salad.jpg
    - assets/images/pasta_aglio_e_olio.jpg
    - assets/images/minestrone_soup.jpg
    - assets/images/eggplant_parmigiana.jpg
    - assets/images/ravioli_sage_butter.jpg
    - assets/images/kabab_koobideh.jpg
    - assets/images/ghormeh_sabzi.jpg
    - assets/images/tahchin.jpg
    - assets/images/zereshk_polo.jpg
    - assets/images/fesenjan.jpg
    - assets/images/bratwurst_sauerkraut.jpg
    - assets/images/wiener_schnitzel.jpg
    - assets/images/kartoffelsalat.jpg
    - assets/images/schweinshaxe.jpg
    - assets/images/kaesespaetzle.jpg
    - assets/images/classic_cheeseburger.jpg
    - assets/images/bbq_pulled_pork.jpg
    - assets/images/macaroni_and_cheese.jpg
    - assets/images/fried_chicken.jpg
    - assets/images/apple_pie.jpg
    - assets/images/coq_au_vin.jpg
    - assets/images/ratatouille.jpg
    - assets/images/croque_monsieur.jpg
    - assets/images/bouillabaisse.jpg
    - assets/images/creme_brulee.jpg
    - assets/images/paella.jpg
    - assets/images/gazpacho.jpg
    - assets/images/tortilla_espanola.jpg
    - assets/images/patatas_bravas.jpg
    - assets/images/churros.jpg
    - assets/images/kebab.jpg
    - assets/images/baklava.jpg
    - assets/images/manti.jpg
    - assets/images/turkish_delight.jpg
    - assets/images/menemen.jpg
    - assets/images/tacos.jpg
    - assets/images/enchiladas.jpg
    - assets/images/guacamole.jpg
    - assets/images/chiles_rellenos.jpg
    - assets/images/elote.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
